services:
  mariadb:
    image: docker-registry.edu.forestier.re/init_mariadb:v1
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=azerty

  nextcloud:
    image: nextcloud:apache
    restart: unless-stopped
    ports:
      - "[::]:8080:80"
    depends_on:
      - mariadb
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud_u
      - MYSQL_PASSWORD=pwd

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - "[::]:8081:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress_u
      - WORDPRESS_DB_PASSWORD=pwd