services:
  mariadb:
    image: ${DOCKER_REGISTRY_URL}/init_mariadb:v1
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  nextcloud:
    image: nextcloud:apache
    labels: # Traefik rules
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.alalves.uca-devops.ovh`)"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${NEXTCLOUD_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_PASSWORD}

  wordpress:
    image: wordpress
    labels: # Traefik rules
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`blog.alalves.uca-devops.ovh`)"
      - "traefik.http.routers.wordpress.entrypoints=https"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=${WORDPRESS_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_PASSWORD}

  go_app:
    image: ${DOCKER_REGISTRY_URL}/go_app:1.0
    labels: # Traefik rules
      - "traefik.enable=true"
      - "traefik.http.routers.goapp.rule=Host(`projet.alalves.uca-devops.ovh`)"
      - "traefik.http.routers.goapp.entrypoints=https"
      - "traefik.http.routers.goapp.tls.certresolver=myresolver"
    restart: unless-stopped

  traefik:
    image: traefik:v3.2
    command:
      - "--api=true"                                                              # Enable Traefik API
      - "--api.dashboard=false"                                                   # Disable the dashboard (access at http://traefik.localhost:8080)
      - "--providers.docker=true"                                                 # Enable automatic discovery of Docker services
      - "--providers.docker.exposedbydefault=false"                               # Containers must be explicitly exposed
      - "--entrypoints.http.address=:80"                                          # Define an HTTP entry point
      - "--entrypoints.https.address=:443"                                        # Define an HTTPS entry point
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"               # Let's Encrypt challenges
      - "--certificatesresolvers.myresolver.acme.email=noreply@forestier.re"      # Let's Encrypt email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"  # Certificate storage
    ports:
      - "[::]:80:80"         # HTTP
      - "[::]:443:443"       # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
      - "./traefik:/etc/traefik"                                                  # Volume for additional files like traefik.yml