-- Initialization of MariaDB with 2 users and 2 databases.

CREATE USER '${NEXTCLOUD_USER}'@'%' IDENTIFIED BY '${NEXTCLOUD_PASSWORD}';
CREATE USER '${WORDPRESS_USER}'@'%' IDENTIFIED BY '${WORDPRESS_PASSWORD}';
CREATE DATABASE nextcloud;
CREATE DATABASE wordpress;
GRANT ALL PRIVILEGES ON nextcloud.* TO '${NEXTCLOUD_USER}'@'%';
GRANT ALL PRIVILEGES ON wordpress.* TO '${WORDPRESS_USER}'@'%';
FLUSH PRIVILEGES;
