- name: List the contents of /home/debian
  hosts: servers
  vars_files:
    - vars/vars_app.yaml
    - vars/vars_secrets.yaml
  roles:
    - geerlingguy.docker          # Role to install Docker
  become: yes

  tasks:
    - name: Create a directory on the VM to contain Docker files
      ansible.builtin.file:
        path: /home/debian/docker
        state: directory

    - name: Create a directory on the VM to contain Docker files
      ansible.builtin.file:
        path: /home/debian/docker/traefik
        state: directory

    - name: Copy local Docker files to the VM
      ansible.builtin.copy:
        src: ./../docker/{{ item }}
        dest: /home/debian/docker/{{ item }}
      with_items: "{{ app_packages }}"

    - name: Copy .env.j2 for Docker Compose environment variables     
      ansible.builtin.template: 
        src: templates/.env.j2                    
        dest: /home/debian/docker/.env

    - name: Copy init.sql.j2 for MariaDB initialization   
      ansible.builtin.template: 
        src: templates/init.sql.j2                   
        dest: /home/debian/docker/init.sql

    - name: Copy prometheus.yml.j2 for Prometheus configuration   
      ansible.builtin.template: 
        src: templates/prometheus.yml.j2            
        dest: /home/debian/docker/prometheus.yml

    - name: Copy traefik.yml.j2 for Traefik configuration   
      ansible.builtin.template: 
        src: templates/traefik.yml.j2            
        dest: /home/debian/docker/traefik/traefik.yml

    - name: Create directory for Traefik certificates
      ansible.builtin.file:
        path: /home/debian/docker/letsencrypt
        state: directory

      # Building Docker images

    - name: Log into private registry and force re-authorization
      docker_login:
        registry: "{{ docker_registry_url }}"
        username: "{{ docker_registry_user }}"
        password: "{{ docker_registry_password }}"
        reauthorize: yes

    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: /home/debian/docker/
        name: "{{ docker_registry_url }}/init_mariadb"
        tag: v1
        push: true
        source: build

    - name: Deploy Docker Compose images
      community.docker.docker_compose_v2:
        project_src: /home/debian/docker/
        files:
          - docker-compose.yml
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output